name: Manual Windows Build & Release for Zed

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install App Installer (to get winget)
        run: |
          Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile winget.msixbundle
          Add-AppxPackage -Path winget.msixbundle

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip1
          override: true

      - name: Install Visual Studio Build Tools (Using Winget)
        run: |
          winget install --id Microsoft.VisualStudio.2022.BuildTools --silent --override `
            "--add Microsoft.VisualStudio.Component.CoreEditor `
             --add Microsoft.VisualStudio.Workload.CoreEditor `
             --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
             --add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake `
             --add Microsoft.VisualStudio.Component.VC.CMake.Project `
             --add Microsoft.VisualStudio.Component.Windows10SDK.20348 `
             --add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre"

      - name: Install CMake
        run: winget install -e --id Kitware.CMake

      - name: Build Zed
        run: cargo build --release

      - name: Package the Binary
        run: |
          mkdir dist
          cp target/release/zed.exe dist/
          cd dist
          Compress-Archive -Path zed.exe -DestinationPath zed-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/zed-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
