name: Manual Windows Build & Release for Zed

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable Long Paths in Git & Windows
        run: |
          git config --system core.longpaths true
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          echo "Long Paths Enabled"

      - name: Set Cargo Home to a Shorter Path
        run: |
          echo "CARGO_HOME=C:/cargo" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "CARGO_TARGET_DIR=C:/cargo-target" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip1
          override: true

      - name: Download & Install Visual Studio Build Tools (MSVC)
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"
          Start-Process -FilePath "vs_buildtools.exe" -ArgumentList `
            "--quiet --wait --norestart `
             --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
             --add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre `
             --add Microsoft.VisualStudio.Component.Windows11SDK.26100 `
             --add Microsoft.VisualStudio.Component.VC.CMake.Project" -NoNewWindow -Wait

      - name: Build Zed
        run: cargo build --release

      - name: Package the Binary
        run: |
          mkdir dist
          cp C:/cargo-target/release/zed.exe dist/
          cd dist
          Compress-Archive -Path zed.exe -DestinationPath zed-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/zed-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
